# Generated by Django 4.0.1 on 2022-03-24 08:29

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0002_delete_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_related_utility', models.CharField(choices=[('Electric Pole', 'Electric Pole'), ('Street Lamp', 'Street Lamp'), ('Transmission Line', 'Transmission Line'), ('Sewerline', 'Sewerline'), ('Water Body', 'Water Body'), (
                    'Septic Tank', 'Septic Tank'), ('Fountain', 'Fountain'), ('Road', 'Road'), ('Ground', 'Ground'), ('Building', 'Building'), ('Boundary', 'Boundary'), ('Other', 'Other')], default='Other', max_length=255)),
                ('description', models.TextField()),
                ('service_required_type', models.CharField(choices=[
                 ('Normal', 'Normal'), ('Emergency', 'Emergency')], default='Normal', max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_solved', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='complaint_registering_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
